"use client";
import { useEffect,useState,useTransition } from "react";
import { addWorkLog,deleteWorkLog,startTimer,stopTimer,updateWorkLog } from "@/app/(app)/phase3-actions";
import { actualRate,formatTokyo,scheduleMinutes,totalWorkMinutes,variance,varianceLabel } from "@/lib/time/phase3";
import type { Task,TaskSchedule,WorkLog } from "@/types/database";

const button="rounded-lg border border-slate-200 px-3 py-2 text-sm hover:bg-slate-50 disabled:opacity-50";
function Clock({start}:{start:string}){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const seconds=Math.max(0,Math.floor((now-new Date(start).getTime())/1000));return <span className="font-mono">{[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,"0")).join(":")}</span>}
export function PlanActualPanel({task,schedules,logs}:{task:Task;schedules:TaskSchedule[];logs:WorkLog[]}){const [pending,go]=useTransition(),[message,setMessage]=useState(""),[custom,setCustom]=useState(25),[note,setNote]=useState("");const actual=totalWorkMinutes(logs),diff=variance(actual,task.estimated_minutes),rate=actualRate(actual,task.estimated_minutes),scheduled=schedules.reduce((n,s)=>n+scheduleMinutes(s),0),running=logs.find(l=>!l.ended_at);const run=(p:Promise<{error?:string;ok?:boolean}>)=>go(async()=>{const r=await p;setMessage(r.error??"保存しました");if(!r.error)location.reload()});return <section className="mt-6 border-t pt-5"><h3 className="font-bold">予定・実績</h3><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Metric label="予定" value={`${task.estimated_minutes??0}分`}/><Metric label="実績" value={`${actual}分`}/><Metric label="差分" value={varianceLabel(diff)} note={diff>0?"超過":diff<0?"短縮":"一致"}/></div><p className="mt-2 text-xs text-slate-500">予定比 {rate===null?"—":`${rate}%`} ・ スケジュール済み {scheduled}分 ・ 未配置 {Math.max(0,(task.estimated_minutes??0)-scheduled)}分</p>
{running?<div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="font-semibold">● 作業中 <Clock start={running.started_at}/></p><input value={note} onChange={e=>setNote(e.target.value)} placeholder="何をしたか（任意）" className="mt-2 w-full rounded-lg border bg-white px-3 py-2 text-sm"/><button disabled={pending} onClick={()=>run(stopTimer(running.id,note))} className="mt-2 rounded-lg bg-slate-800 px-4 py-2 text-sm text-white">■ 作業終了</button></div>:<button disabled={pending} onClick={()=>run(startTimer(task.id))} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">▶ 作業開始</button>}
<div className="mt-4"><p className="text-sm font-semibold">実績を追加</p><div className="mt-2 flex flex-wrap gap-2">{[15,30,60].map(m=><button className={button} disabled={pending} key={m} onClick={()=>run(addWorkLog(task.id,m))}>+{m}分</button>)}<input aria-label="任意の分数" type="number" min="1" value={custom} onChange={e=>setCustom(Number(e.target.value))} className="w-20 rounded-lg border px-2 text-sm"/><button className={button} disabled={pending} onClick={()=>run(addWorkLog(task.id,custom))}>追加</button></div></div>
<div className="mt-5"><p className="text-sm font-semibold">スケジュール</p>{schedules.length?schedules.map(s=><p className="mt-2 text-sm" key={s.id}>{formatTokyo(s.start_at,{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}〜{formatTokyo(s.end_at,{hour:"2-digit",minute:"2-digit"})}（{scheduleMinutes(s)}分）</p>):<p className="mt-2 text-sm text-slate-400">予定はまだ配置されていません</p>}</div>
<div className="mt-5"><p className="text-sm font-semibold">作業履歴</p>{logs.filter(l=>l.ended_at).length?logs.filter(l=>l.ended_at).map(l=><LogRow key={l.id} log={l} run={run}/>):<p className="mt-2 text-sm text-slate-400">まだ作業記録がありません</p>}</div>{message&&<p role="status" className={`mt-3 text-sm ${message==="保存しました"?"text-emerald-700":"text-red-600"}`}>{message}</p>}</section>}
function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-lg bg-slate-50 p-2"><p className="text-xs text-slate-500">{label}</p><p className="font-bold">{value}</p>{note&&<p className="text-xs">{note}</p>}</div>}
function LogRow({log,run}:{log:WorkLog;run:(p:Promise<{error?:string;ok?:boolean}>)=>void}){const edit=()=>{const minutes=Number(prompt("分数",String(log.minutes??0)));if(!minutes||!log.ended_at)return;const end=new Date(log.ended_at),start=new Date(end.getTime()-minutes*60000),note=prompt("何をしたか",log.note??"")??log.note??"";run(updateWorkLog(log.id,{startedAt:start.toISOString(),endedAt:end.toISOString(),note}))};return <div className="mt-2 rounded-lg border p-3 text-sm"><div className="flex items-center gap-2"><span className="flex-1">{formatTokyo(log.started_at,{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}〜{formatTokyo(log.ended_at!,{hour:"2-digit",minute:"2-digit"})} <b>{log.minutes??0}分</b></span><button onClick={edit}>編集</button><button className="text-red-600" onClick={()=>run(deleteWorkLog(log.id))}>削除</button></div>{log.note&&<p className="mt-1 text-slate-500">{log.note}</p>}</div>}
