"use client";
import { useState,useTransition } from "react";
import { saveProgress } from "@/app/(app)/tasks/actions";
import { saveReflection,type ReflectionInput } from "@/app/(app)/reflections/actions";
import type { ProgressLog,Reflection,Task } from "@/types/database";
import { DatabaseUpdating } from "@/components/ui/database-updating";
const input="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-indigo-500";
const empty:ReflectionInput={result:"",good_points:"",problems:"",improvements:"",next_action:""};
export function ProgressReflectionPanel({task,history,reflection}:{task:Task;history:ProgressLog[];reflection:Reflection|null}){const[progress,setProgress]=useState(task.progress),[note,setNote]=useState(""),[form,setForm]=useState<ReflectionInput>(reflection?{result:reflection.result??"",good_points:reflection.good_points??"",problems:reflection.problems??"",improvements:reflection.improvements??"",next_action:reflection.next_action??""}:empty),[message,setMessage]=useState(""),[pending,start]=useTransition();const run=(action:Promise<{error?:string;ok?:boolean}>)=>start(async()=>{const result=await action;if(result.error)setMessage(`保存できませんでした: ${result.error}（入力内容は保持されています）`);else{setMessage("保存しました");location.reload();}});return <div className="mt-6 space-y-6 border-t pt-6"><DatabaseUpdating active={pending} />
<section><div className="flex items-center justify-between gap-4"><h3 className="font-bold">進捗</h3><output className="shrink-0 text-sm font-bold text-indigo-700" htmlFor="progress-slider">{progress}%</output></div><input id="progress-slider" aria-label="進捗スライダー" className="mt-3 block w-full accent-indigo-600" type="range" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/><textarea className={`${input} mt-2`} value={note} onChange={e=>setNote(e.target.value)} placeholder="進捗メモ（任意）"/><button disabled={pending||progress===task.progress} onClick={()=>run(saveProgress(task.id,progress,note))} className="mt-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">進捗を保存</button>{task.status!=="done"&&<button disabled={pending} onClick={()=>run(saveProgress(task.id,100,note))} className="ml-2 rounded-lg border border-indigo-200 px-4 py-2 text-sm font-semibold text-indigo-700">完了して振り返る</button>}</section>
<section><h3 className="font-bold">進捗履歴</h3>{history.length?<><div className="mt-3 flex h-20 items-end gap-1 rounded-lg bg-slate-50 p-2" aria-label="進捗推移">{[...history].reverse().map(h=><div key={h.id} title={`${h.progress}%`} className="min-w-2 flex-1 rounded-t bg-indigo-400" style={{height:`${Math.max(4,h.progress)}%`}}/>)}</div><div className="mt-2 divide-y">{history.map(h=><div key={h.id} className="py-2 text-sm"><span className="text-slate-400">{new Date(h.created_at).toLocaleString("ja-JP")}</span><b className="ml-3">{h.progress}%</b>{h.note&&<p>{h.note}</p>}</div>)}</div></>:<p className="mt-2 text-sm text-slate-400">まだ進捗履歴がありません</p>}</section>
<section id="reflection"><h3 className="font-bold">振り返り</h3>{!reflection&&<p className="mt-1 text-sm text-slate-400">このTaskはまだ振り返りがありません</p>}<div className="mt-3 space-y-3">{([["result","結果"],["good_points","良かったこと"],["problems","問題・原因"],["improvements","改善方法"],["next_action","次にやること"]] as const).map(([key,label])=><label key={key} className="block text-sm font-medium text-slate-600">{label}<textarea className={`${input} mt-1 min-h-20`} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button disabled={pending} onClick={()=>run(saveReflection(task.id,form))} className="w-full rounded-lg bg-emerald-600 py-2.5 font-semibold text-white disabled:opacity-50">振り返りを保存</button></div></section>{message&&<p role="status" className={message.startsWith("保存でき")?"text-sm text-red-600":"text-sm text-emerald-600"}>{message}</p>}</div>}
