"use client";
import { useMemo, useRef, useState, useTransition } from "react";
import { createTask, deleteTask, importTasks, toggleTask, updateTask, type TaskInput } from "@/app/(app)/tasks/actions";
import { buildTaskTree, descendantCount, taskCheckState, type TaskNode } from "@/lib/tasks/tree";
import { parseMarkdown, toMarkdown } from "@/lib/tasks/markdown";
import type { Project, Task, TaskPriority, TaskStatus } from "@/types/database";

const statusLabel = { todo: "未着手", doing: "進行中", done: "完了" }; const priorityLabel = { low: "低", medium: "中", high: "高" };
const inputClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm focus:border-indigo-500 outline-none";
function localDate(value: string | null) { if (!value) return ""; const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }

export function TaskManager({ initialTasks, projects }: { initialTasks: Task[]; projects: Project[] }) {
  const [tasks, setTasks] = useState(initialTasks); const [filter, setFilter] = useState<"all"|TaskStatus>("all"); const [project, setProject] = useState(""); const [priority, setPriority] = useState(""); const [sort, setSort] = useState("created");
  const [selected, setSelected] = useState<Task | null>(null); const [quick, setQuick] = useState(""); const [notice, setNotice] = useState(""); const [importOpen, setImportOpen] = useState(false); const [markdown, setMarkdown] = useState(""); const [pending, startTransition] = useTransition();
  const shown = useMemo(() => tasks.filter(t => (filter === "all" || t.status === filter) && (!project || t.project_id === project) && (!priority || t.priority === priority)).sort((a,b) => sort === "due" ? (a.due_at ?? "9999").localeCompare(b.due_at ?? "9999") : sort === "priority" ? ({high:0,medium:1,low:2}[a.priority]-({high:0,medium:1,low:2}[b.priority])) : a.created_at.localeCompare(b.created_at)), [tasks, filter, project, priority, sort]);
  const tree = useMemo(() => buildTaskTree(shown), [shown]);
  const run = (action: Promise<{error?: string; ok?: boolean}>, optimistic?: () => void) => startTransition(async () => { const previous = tasks; optimistic?.(); const result = await action; if (result.error) { setTasks(previous); setNotice(`エラー: ${result.error}`); } else { setNotice("保存しました"); location.reload(); } });
  const add = (parent_id: string | null = null) => { const title = prompt(parent_id ? "子タスクのタイトル" : "タスクのタイトル"); if (title) run(createTask({ title, parent_id, project_id: project || null })); };
  const sibling = (node: TaskNode) => { const title = prompt("同階層タスクのタイトル"); if (title) run(createTask({ title, parent_id: node.parent_id, project_id: node.project_id })); };
  const exportText = async () => { const text = toMarkdown(tree); await navigator.clipboard.writeText(text); setNotice(`${tree.length ? "表示中のタスクを" : "空の内容を"}コピーしました`); };
  return <div className="space-y-4">
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <form onSubmit={e => { e.preventDefault(); if (quick.trim()) run(createTask({title: quick, project_id: project || null})); }} className="flex gap-2"><input value={quick} onChange={e=>setQuick(e.target.value)} className={inputClass} placeholder="＋ タスクをすばやく追加" aria-label="タスク名"/><button disabled={pending} className="shrink-0 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">追加</button></form>
      <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} className={inputClass}><option value="all">すべて</option><option value="todo">未着手</option><option value="doing">進行中</option><option value="done">完了</option></select><select value={project} onChange={e=>setProject(e.target.value)} className={inputClass}><option value="">全プロジェクト</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className={inputClass}><option value="">全優先度</option><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select><select value={sort} onChange={e=>setSort(e.target.value)} className={inputClass}><option value="created">作成順</option><option value="due">期限順</option><option value="priority">優先度順</option></select><div className="flex gap-2"><button onClick={()=>setImportOpen(true)} type="button" className="flex-1 rounded-lg border border-slate-200 px-3 text-sm">Import</button><button onClick={exportText} type="button" className="flex-1 rounded-lg border border-slate-200 px-3 text-sm">Export</button></div></div>
    </div>
    {notice && <div role="status" className={`rounded-lg px-4 py-2 text-sm ${notice.startsWith("エラー")?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{notice}<button onClick={()=>setNotice("")} className="float-right">×</button></div>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{tree.length ? <div>{tree.map(n=><TaskRow key={n.id} node={n} projects={projects} onSelect={setSelected} onToggle={(node, done)=>run(toggleTask(node.id,done),()=>setTasks(current=>current.map(t=>t.id===node.id?{...t,status:done?"done":"todo",progress:done?100:0}:t)))} onAdd={add} onSibling={sibling} onDelete={node=>{ const count=descendantCount(tasks,node.id); if(confirm(count?`このタスクと${count}件の子タスクを削除しますか？`:"このタスクを削除しますか？")) run(deleteTask(node.id)); }}/>)}</div> : <div className="grid min-h-64 place-items-center p-8 text-center"><div><p className="font-semibold">タスクがありません</p><p className="mt-2 text-sm text-slate-500">最初のタスクを追加しましょう。</p><button onClick={()=>add()} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">＋ タスクを追加</button></div></div>}</section>
    {selected && <TaskDrawer task={selected} projects={projects} onClose={()=>setSelected(null)} onSave={input=>run(updateTask(selected.id,input))}/>} 
    {importOpen && <ImportDialog markdown={markdown} setMarkdown={setMarkdown} onClose={()=>setImportOpen(false)} onImport={()=>run(importTasks(markdown,project||undefined))}/>} 
  </div>;
}

function TaskRow({node,projects,onSelect,onToggle,onAdd,onSibling,onDelete}:{node:TaskNode;projects:Project[];onSelect:(t:Task)=>void;onToggle:(t:TaskNode,d:boolean)=>void;onAdd:(id:string)=>void;onSibling:(t:TaskNode)=>void;onDelete:(t:TaskNode)=>void}) {
  const checkbox=useRef<HTMLInputElement>(null); const state=taskCheckState(node); if(checkbox.current) checkbox.current.indeterminate=state==="indeterminate";
  return <><article className={`group border-b border-slate-100 px-3 py-3 hover:bg-slate-50 ${node.status==="done"?"opacity-55":""}`} style={{paddingLeft:`${12+node.depth*24}px`}}><div className="flex items-start gap-3"><input ref={checkbox} type="checkbox" checked={state==="checked"} onChange={e=>onToggle(node,e.target.checked)} className="mt-1 size-4 accent-indigo-600"/><button onClick={()=>onSelect(node)} className="min-w-0 flex-1 text-left"><span className={`block truncate text-sm font-medium ${node.status==="done"?"line-through":""}`}>{node.title}</span><span className="mt-1 flex flex-wrap gap-2 text-xs text-slate-400"><span>{statusLabel[node.status]}</span><span>優先度 {priorityLabel[node.priority]}</span>{node.project_id&&<span>{projects.find(p=>p.id===node.project_id)?.name}</span>}{node.due_at&&<span>期限 {localDate(node.due_at)}</span>}<span>{node.progress}%</span></span></button><div className="flex shrink-0 gap-1"><button onClick={()=>onSelect(node)} title="編集" className="rounded p-1.5 text-slate-400 hover:bg-slate-200">✎</button>{node.depth<2&&<button onClick={()=>onAdd(node.id)} title="子タスクを追加" className="rounded p-1.5 text-slate-400 hover:bg-slate-200">＋子</button>}<button onClick={()=>onSibling(node)} title="同階層を追加" className="hidden rounded p-1.5 text-xs text-slate-400 hover:bg-slate-200 sm:block">＋同</button><button onClick={()=>onDelete(node)} title="削除" className="rounded p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600">×</button></div></div></article>{node.children.map(c=><TaskRow key={c.id} node={c} projects={projects} onSelect={onSelect} onToggle={onToggle} onAdd={onAdd} onSibling={onSibling} onDelete={onDelete}/>)}</>;
}

function TaskDrawer({task,projects,onClose,onSave}:{task:Task;projects:Project[];onClose:()=>void;onSave:(i:TaskInput)=>void}) { const [form,setForm]=useState({...task,due_at:localDate(task.due_at)}); const set=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value})); return <div className="fixed inset-0 z-40 bg-slate-900/30" onMouseDown={onClose}><aside onMouseDown={e=>e.stopPropagation()} className="ml-auto h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">タスク詳細</h2><button onClick={onClose} className="text-2xl text-slate-400">×</button></div><form onSubmit={e=>{e.preventDefault();onSave({...form,due_at:form.due_at?new Date(`${form.due_at}T23:59:59`).toISOString():null});onClose();}} className="mt-6 space-y-4"><Field label="タイトル"><input required value={form.title} onChange={e=>set("title",e.target.value)} className={inputClass}/></Field><Field label="説明"><textarea value={form.description??""} onChange={e=>set("description",e.target.value)} className={`${inputClass} min-h-24`}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Project"><select value={form.project_id??""} onChange={e=>set("project_id",e.target.value||null)} className={inputClass}><option value="">なし</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="優先度"><select value={form.priority} onChange={e=>set("priority",e.target.value)} className={inputClass}>{Object.entries(priorityLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="ステータス"><select value={form.status} onChange={e=>set("status",e.target.value)} className={inputClass}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="進捗 (%)"><input type="number" min="0" max="100" value={form.progress} onChange={e=>set("progress",Number(e.target.value))} className={inputClass}/></Field><Field label="予定時間 (分)"><input type="number" min="0" value={form.estimated_minutes??""} onChange={e=>set("estimated_minutes",e.target.value?Number(e.target.value):null)} className={inputClass}/></Field><Field label="期限"><input type="date" value={form.due_at} onChange={e=>set("due_at",e.target.value)} className={inputClass}/></Field></div><button className="w-full rounded-lg bg-indigo-600 py-2.5 font-semibold text-white">変更を保存</button></form></aside></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block text-sm font-medium text-slate-600">{label}<div className="mt-1.5">{children}</div></label>; }
function ImportDialog({markdown,setMarkdown,onClose,onImport}:{markdown:string;setMarkdown:(v:string)=>void;onClose:()=>void;onImport:()=>void}) { const preview=parseMarkdown(markdown); return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-900/40 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold">Markdown Import</h2><p className="mt-1 text-sm text-slate-500">2スペースのインデントで最大3階層まで読み込みます。</p><textarea autoFocus value={markdown} onChange={e=>setMarkdown(e.target.value)} className={`${inputClass} mt-4 min-h-48 font-mono`} placeholder={'- [ ] AWS学習\n  - [x] EC2'}/><p className="mt-2 text-sm">プレビュー: {preview.length}件（完了 {preview.filter(t=>t.done).length}件）</p><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">キャンセル</button><button disabled={!preview.length} onClick={()=>{onImport();onClose();}} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white disabled:opacity-50">読み込む</button></div></section></div>; }
