"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { WbsItem } from "@/lib/wbs/types";
import { nextWbsCode } from "@/lib/wbs/hierarchy";
import { saveWbsItem } from "@/app/(app)/wbs/actions";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";

const control = "mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500";
export function WbsItemEditor({ projectId, item, parentId, items, onClose }: { projectId: string; item: WbsItem | null; parentId: string | null; items: WbsItem[]; onClose: () => void }) {
  const router = useRouter();
  const [error, setError] = useState("");
  const [wbsCodeError, setWbsCodeError] = useState("");
  const [pending, setPending] = useState(false);
  const initialCode=item?.wbs_code??nextWbsCode(items,parentId); const descendantCount=item?.wbs_code?items.filter(candidate=>candidate.wbs_code?.startsWith(`${item.wbs_code}.`)).length:0;
  const hasChildren=!!item&&items.some(candidate=>candidate.parent_id===item.id);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <form action={async (form) => { const nextCode=String(form.get("wbs_code")??"").trim(); if(item&&nextCode!==initialCode&&descendantCount&&!confirm(`WBS番号を変更すると、配下の子項目 ${descendantCount}件の番号も変更されます。続けますか？`))return; setPending(true); setError(""); setWbsCodeError(""); const result = await saveWbsItem(projectId, item?.id ?? null, parentId, form); setPending(false); if (result?.error) { if ("field" in result && result.field === "wbs_code") setWbsCodeError(result.error); else setError(result.error); } else { onClose(); router.refresh(); } }} role="dialog" aria-modal="true" aria-labelledby="editor-title" className="flex max-h-[calc(100vh-2rem)] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl">
      <header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 id="editor-title" className="text-lg font-semibold text-slate-950">{item ? "WBS項目を編集" : "WBS項目を追加"}</h2><p className="mt-1 text-xs text-slate-500">工程の内容と進捗を設定します。</p></div><button type="button" aria-label="閉じる" onClick={onClose} className="grid size-9 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-indigo-500"><Icon name="close" className="size-5" /></button></header>
      <div className="flex-1 overflow-y-auto p-5"><div className="space-y-7"><Section title="基本情報"><Field label="WBS番号" name="wbs_code" value={initialCode} error={wbsCodeError} /><Field label="タスク名" name="name" value={item?.name} required /><p className="-mt-2 text-xs text-slate-500 sm:col-span-2">例: 1.1.3。空欄なら自動採番します。上位階層がない番号や重複番号は保存できません。</p><Area label="説明" name="description" value={item?.description} className="sm:col-span-2" /></Section><Section title="スケジュール"><Field label="開始日" name="start_date" type="date" value={item?.start_date} /><Field label="終了日" name="end_date" type="date" value={item?.end_date} /><Field label="担当" name="owner_name" value={item?.owner_name} className="sm:col-span-2" /></Section><Section title="進捗">
        <label className="text-sm font-medium text-slate-700">状態<select name="status" defaultValue={item?.status ?? "not_started"} disabled={hasChildren} className={`${control} disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500`}><option value="not_started">未着手</option><option value="in_progress">進行中</option><option value="completed">完了</option><option value="on_hold">保留</option></select></label>
        <Field label="進捗（%）" name="progress" type="number" value={item?.progress ?? 0} min="0" max="100" disabled={hasChildren} />{hasChildren&&<p className="-mt-2 text-xs text-slate-500 sm:col-span-2">親タスクの状態と進捗は、子タスクの状態と平均進捗から自動計算されます。</p>}</Section><Section title="工数"><Field label="予定工数（h）" name="estimate_hours" type="number" value={item?.estimate_hours} step="0.01" min="0" disabled={hasChildren} /><Field label="実績工数（h）" name="actual_hours" type="number" value={item?.actual_hours} step="0.01" min="0" disabled={hasChildren} />{hasChildren&&<p className="-mt-2 text-xs text-slate-500 sm:col-span-2">親タスクの工数は子タスクの合計から自動計算されるため編集できません。</p>}</Section><Section title="備考"><Area label="備考" name="note" value={item?.note} className="sm:col-span-2" /></Section></div>{error && <p className="mt-4 text-sm text-red-600" role="alert">{error}</p>}</div>
      <footer className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4"><Button type="button" variant="secondary" onClick={onClose}>キャンセル</Button><Button disabled={pending}>{pending ? "保存中…" : "保存"}</Button></footer>
    </form>
  </div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="border-b border-slate-200 pb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{children}</div></section>; }
function Field({ label, value, className = "", error, ...props }: { label: string; name: string; value?: string | number | null; type?: string; required?: boolean; min?: string; max?: string; step?: string; disabled?: boolean; className?: string; error?: string }) { const errorId=`${props.name}-error`; return <label className={`text-sm font-medium text-slate-700 ${className}`}>{label}{props.required && <span className="text-red-600"> *</span>}<input {...props} defaultValue={value ?? ""} aria-invalid={error?true:undefined} aria-describedby={error?errorId:undefined} className={`${control} disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500 ${error?"border-red-400 focus:border-red-500":""}`} />{error&&<span id={errorId} className="mt-1.5 block text-xs font-normal text-red-600" role="alert">{error}</span>}</label>; }
function Area({ label, name, value, className = "" }: { label: string; name: string; value?: string | null; className?: string }) { return <label className={`text-sm font-medium text-slate-700 ${className}`}>{label}<textarea name={name} defaultValue={value ?? ""} rows={3} className={control} /></label>; }
