"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { createClient } from "@/lib/supabase/server";
async function context(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("認証が必要です");return {db,user}}
const message=(error:string)=>{if(error.includes("project_not_found"))return "プロジェクトが見つかりません。共有コードを確認してください。";if(error.includes("join_disabled"))return "現在このプロジェクトへの参加は許可されていません。";if(error.includes("already_"))return "すでに参加済み、または所有者です。";if(error.includes("request_pending"))return "参加申請はすでに送信済みです。";return "処理を完了できませんでした。"}
export async function createWbsProject(form:FormData){const {db,user}=await context();const name=String(form.get("name")??"").trim(),description=String(form.get("description")??"").trim();if(!name)throw new Error("プロジェクト名を入力してください。");const bytes=crypto.getRandomValues(new Uint8Array(8));const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const token=Array.from(bytes,b=>alphabet[b%alphabet.length]).join("");const {data,error}=await db.from("wbs_projects").insert({name,description:description||null,owner_user_id:user.id,share_code:`WBSP-${token.slice(0,4)}-${token.slice(4)}`}).select("id").single();if(error)throw new Error("WBSを作成できませんでした。");redirect(`/wbs/${data.id}`)}
export async function joinWbsProject(_:unknown,form:FormData){const {db}=await context();const {data,error}=await db.rpc("join_wbs_project",{p_share_code:String(form.get("shareCode")??"").trim().toUpperCase()});if(error)return {error:message(error.message)};revalidatePath("/wbs");return {ok:data==="pending"?"参加申請を送信しました。プロジェクト所有者の承認をお待ちください。":"プロジェクトに参加しました。"}}
export async function saveWbsItem(projectId:string,itemId:string|null,parentId:string|null,form:FormData){const {db,user}=await context();const status=String(form.get("status")??"not_started"),progress=status==="completed"?100:Number(form.get("progress")??0);const values={project_id:projectId,parent_id:parentId,name:String(form.get("name")??"").trim(),description:String(form.get("description")??"")||null,start_date:String(form.get("start_date")??"")||null,end_date:String(form.get("end_date")??"")||null,owner_name:String(form.get("owner_name")??"")||null,status,progress,estimate_hours:Number(form.get("estimate_hours"))||null,actual_hours:Number(form.get("actual_hours"))||null,note:String(form.get("note")??"")||null,created_by:user.id};const result=itemId?await db.from("wbs_items").update(values).eq("id",itemId):await db.from("wbs_items").insert(values);if(result.error)return {error:"項目を保存できませんでした。入力内容と権限を確認してください。"};revalidatePath(`/wbs/${projectId}`);return {ok:true}}
export async function deleteWbsItem(projectId:string,itemId:string){const {db}=await context();const {error}=await db.from("wbs_items").delete().eq("id",itemId);if(error)return {error:"項目を削除できませんでした。"};revalidatePath(`/wbs/${projectId}`);return {ok:true}}
export async function deleteWbsProject(projectId:string){const {db}=await context();const {error}=await db.from("wbs_projects").delete().eq("id",projectId);if(error)return {error:"プロジェクトを削除できませんでした。"};redirect("/wbs")}
